name: CI/CD

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'spec/**'
      - '.github/workflows/update-spec.yml'

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        run: cp example.env .env
      - name: Start containers
        run: docker-compose up -d --build
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install test dependencies
        run: npm install -g httpyac
      - name: Wait for docker
        run: while docker ps | grep -E -q "unhealthy|starting"; do sleep 1s; done
      - name: Run integration tests
        # run twice to check if the tests are idempotent (e.g., cache)
        run: |
          httpyac --all -o short --bail test/integration/**/*.http
          httpyac --all -o short --bail test/integration/**/*.http
      - name: Print docker logs
        # just for debugging etc.
        run: docker-compose logs
      - name: Export docker logs
        if: failure()
        run: docker-compose -f "prod.docker-compose.yml" logs --no-color > docker-compose.log
      - name: Upload docker logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose.log
          path: docker-compose.log
      - name: Stop containers
        if: always()
        run: docker-compose down
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: SSH and update
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 20m
          script: |
            set -e
            cd /home/nlp-apis/sentence-similarity-api
            git pull -X theirs https://oauth2:${{ secrets.GH_TOKEN }}@github.com/toppev/sentence-similarity-api.git || git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/toppev/sentence-similarity-api.git . 
            docker-compose up --build -d
            docker image prune -f