name: CI/CD

on:
  push:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        run: cp dev.env .env
      - name: Start containers
        run: docker-compose up -d --build
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install test dependencies
        run: npm install -g httpyac
      - name: Wait for docker
        run: while docker ps | grep -q "unhealthy"; do sleep 1s; done
      - name: Run integration tests
        run: httpyac --all -o short --repeat 5 --repeat-mode sequential --bail test/integration/**/*.http