name: CI/CD

on:
  push:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        run: cp example.env .env
      - name: Start containers
        run: docker-compose up -d --build
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install test dependencies
        run: npm install -g httpyac
      - name: Wait for docker
        run: while docker ps | grep -E -q "unhealthy|starting"; do sleep 1s; done
      - name: Run integration tests
        # run twice to check if the tests are idempotent (e.g., cache)
        run: |
          httpyac --all -o short --bail test/integration/**/*.http
          httpyac --all -o short --bail test/integration/**/*.http
      - name: Upload docker logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose.log
          path: docker-compose.log
      - name: Stop containers
        if: always()
        run: docker-compose down