name: Update spec

on:
  push:
    branches:
      - main
    paths:
      - 'spec/*'
      - '.github/workflows/update-spec.yml'

jobs:
  update-spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update OpenAPI spec to RapidAPI
        # TODO: make it actually fail on non 2xx status code
        run: |
          curl --request PUT \
            --url https://openapi-provisioning.p.rapidapi.com/v1/apis/${{ secrets.RAPIDAPI_API_ID }} \
            --header 'X-RapidAPI-Host: openapi-provisioning.p.rapidapi.com' \
            --header 'X-RapidAPI-Key: ${{ secrets.RAPIDAPI_KEY }}' \
            --header 'content-type: multipart/form-data' \
            --form file=@spec/openapi.yaml \